"use client";

import { useCallback, useMemo, useRef, useState } from "react";
import { Maximize2, Minus, Plus } from "lucide-react";
import { layout } from "@/lib/diagram/layout";
import { renderSvg } from "@/lib/diagram/svg";
import type { DiagramTheme } from "@/lib/diagram/theme";
import type { Diagram } from "@/lib/diagram/types";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { renderTikz } from "@/lib/diagram/latex";
import { ExportMenu } from "./export-menu";

/**
 * A diagram on screen.
 *
 * THE SVG IS INJECTED AS A STRING, NOT BUILT AS JSX, and that is the whole point.
 * The alternative — a React tree for the screen plus a serializer for the export —
 * is two renderers, and two renderers drift: the exported file grows a stroke
 * width the screen never had, and nobody notices until it is in a submitted
 * report. Here the bytes on screen ARE the bytes in the file.
 *
 * `dangerouslySetInnerHTML` is safe here in the way that word rarely is: the
 * markup is generated by `svg.ts` from a `Diagram` object, and every string that
 * reaches it goes through that module's escaper. Nothing user-typed is ever
 * interpolated into markup unescaped — see the escaping test in `diagram.test.ts`.
 */

const MIN_ZOOM = 0.25;
const MAX_ZOOM = 4;

export function DiagramFigure({
  diagram,
  theme,
  className,
  maxHeight = 520,
  toolbar = true,
}: {
  diagram: Diagram;
  theme: DiagramTheme;
  className?: string;
  maxHeight?: number;
  toolbar?: boolean;
}) {
  const placed = useMemo(() => layout(diagram, theme), [diagram, theme]);
  const svg = useMemo(() => renderSvg(placed, theme), [placed, theme]);

  const [zoom, setZoom] = useState(1);
  const [pan, setPan] = useState({ x: 0, y: 0 });
  const drag = useRef<{ x: number; y: number; from: { x: number; y: number } } | null>(
    null,
  );
  const [dragging, setDragging] = useState(false);

  const reset = useCallback(() => {
    setZoom(1);
    setPan({ x: 0, y: 0 });
  }, []);

  const nudge = (factor: number) =>
    setZoom((z) => Math.min(MAX_ZOOM, Math.max(MIN_ZOOM, z * factor)));

  // Wheel zoom is deliberately gated on Ctrl/Cmd. A diagram taller than the
  // viewport is normal here, and hijacking a plain scroll would trap the page.
  const onWheel = (e: React.WheelEvent) => {
    if (!e.ctrlKey && !e.metaKey) return;
    e.preventDefault();
    setZoom((z) => Math.min(MAX_ZOOM, Math.max(MIN_ZOOM, z * Math.exp(-e.deltaY * 0.002))));
  };

  const onPointerDown = (e: React.PointerEvent) => {
    if (e.button !== 0) return;
    drag.current = { x: e.clientX, y: e.clientY, from: pan };
    setDragging(true);
    e.currentTarget.setPointerCapture(e.pointerId);
  };
  const onPointerMove = (e: React.PointerEvent) => {
    const d = drag.current;
    if (!d) return;
    setPan({ x: d.from.x + (e.clientX - d.x), y: d.from.y + (e.clientY - d.y) });
  };
  const onPointerUp = () => {
    drag.current = null;
    setDragging(false);
  };

  return (
    <figure className={cn("bg-card overflow-hidden rounded-md border", className)}>
      {toolbar && (
        <div className="bg-muted/40 flex items-center gap-1 border-b px-2 py-1.5">
          <span className="truncate pr-2 text-xs font-medium">{diagram.title}</span>
          <div className="ml-auto flex items-center gap-1">
            <Button
              variant="ghost"
              size="icon"
              className="size-7"
              onClick={() => nudge(1 / 1.25)}
              aria-label="Zoom out"
            >
              <Minus className="size-3.5" />
            </Button>
            <span className="text-muted-foreground w-10 text-center font-mono text-[11px] tabular-nums">
              {Math.round(zoom * 100)}%
            </span>
            <Button
              variant="ghost"
              size="icon"
              className="size-7"
              onClick={() => nudge(1.25)}
              aria-label="Zoom in"
            >
              <Plus className="size-3.5" />
            </Button>
            <Button
              variant="ghost"
              size="icon"
              className="size-7"
              onClick={reset}
              aria-label="Fit"
            >
              <Maximize2 className="size-3.5" />
            </Button>
            <ExportMenu
              svg={svg}
              name={diagram.id}
              theme={theme}
              latex={(form) =>
                renderTikz(placed, theme, {
                  standalone: form === "standalone",
                  background: form === "standalone" && theme.background !== "none",
                })
              }
            />
          </div>
        </div>
      )}

      <div
        className={cn(
          "diagram-viewport relative overflow-hidden",
          dragging ? "cursor-grabbing" : "cursor-grab",
        )}
        style={{ maxHeight }}
        onWheel={onWheel}
        onPointerDown={onPointerDown}
        onPointerMove={onPointerMove}
        onPointerUp={onPointerUp}
        onPointerCancel={onPointerUp}
      >
        <div
          className="diagram-figure origin-top-left"
          style={{
            transform: `translate(${pan.x}px, ${pan.y}px) scale(${zoom})`,
            transformOrigin: "0 0",
          }}
          // See the note at the top of this file: the markup is generated by
          // svg.ts, which escapes every string it embeds.
          dangerouslySetInnerHTML={{ __html: svg }}
        />
      </div>

      {/* No figcaption here on purpose: the caption and the notes are drawn
          INSIDE the SVG, so that they travel with the exported file. Repeating
          them in the page chrome would show every reader the same sentence
          twice, and the two would drift the moment the theme hid one of them. */}
    </figure>
  );
}
